#NumPy

NumPy is one of the python library

**Array**


An array is a data structure that stores values of same data type. In Python, this is the main difference between arrays and lists. While python lists can contain values corresponding to different data types, arrays in python can only contain values corresponding to same data type

In [0]:
import numpy as np

In [0]:
x=np.array([1,2,3])
print(x)

[1 2 3]


In [0]:
type(x)

numpy.ndarray

In [0]:
l=[4,5,6]
x=np.asarray(l)
type(x)

numpy.ndarray

In [0]:
print(x)

[4 5 6]


In [0]:
x=np.asarray(l,float)
print(x)

[4. 5. 6.]


In [0]:
x.shape

(3,)

In [0]:
x=np.array([[1,2,3],[4,5,6]])
print(x)

[[1 2 3]
 [4 5 6]]


In [0]:
x.shape

(2, 3)

In [0]:
x[0,2]

3

In [0]:
x[0,:]

array([1, 2, 3])

In [0]:
y=np.array([[1,4,7],[2,5,8],[3,6,9]])
print(y)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [0]:
y.shape

(3, 3)

In [0]:
x=np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [0]:
x=np.eye(3,3)

In [0]:
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [0]:
x=np.random.random((3,3))

In [0]:
print(x)

[[0.49857839 0.4092445  0.56372825]
 [0.25019019 0.60392014 0.19257479]
 [0.32315285 0.31211709 0.74439531]]


In [0]:
z=x.T

In [0]:
print(z)

[[0.49857839 0.25019019 0.32315285]
 [0.4092445  0.60392014 0.31211709]
 [0.56372825 0.19257479 0.74439531]]


In [0]:
y=x.reshape(9,1)

In [0]:
print(y)

[[0.49857839]
 [0.4092445 ]
 [0.56372825]
 [0.25019019]
 [0.60392014]
 [0.19257479]
 [0.32315285]
 [0.31211709]
 [0.74439531]]


In [0]:
A=np.arange(5)

In [0]:
B=np.arange(5)

In [0]:
C=A+B
D=A-B
E=A*B

In [0]:
print(C,D,E)

[0 2 4 6 8] [0 0 0 0 0] [ 0  1  4  9 16]


In [0]:
print(A,A+1)

[0 1 2 3 4] [1 2 3 4 5]


In [0]:
A=np.random.random((2,3))                                                        #random float values                                                
print(A)
print(A+1)

[[0.57810177 0.2122424  0.95243273]
 [0.9326733  0.01032108 0.18012226]]
[[1.57810177 1.2122424  1.95243273]
 [1.9326733  1.01032108 1.18012226]]


In [0]:
A=np.floor(np.random.random((2,3))*10)

In [0]:
print(A)

[[4. 6. 7.]
 [9. 1. 4.]]


In [0]:
U=[1,2,-1]
V=[2,-1,3]

In [0]:
p=np.inner(U,V)
print(p)

-3


In [0]:
P1=np.outer(U,V)
print(P1)

[[ 2 -1  3]
 [ 4 -2  6]
 [-2  1 -3]]


In [0]:
A=np.ones((2,3))
B=np.ones((3,2))
np.dot(A,B)

array([[3., 3.],
       [3., 3.]])

In [0]:
np.dot(A.T,B.T)

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

In [0]:
A=np.ones((2,3))
print(A)

[[1. 1. 1.]
 [1. 1. 1.]]


In [0]:
A.sum()

6.0

In [0]:
A.sum(axis=1)

array([3., 3.])

In [0]:
A.sum(axis=0)

array([2., 2., 2.])

In [0]:
A.max()

1.0